//! Asset inclusion is generated by Rust's own string escaping, not a JS Rust-code interpolator.
use std::{env, fs, path::PathBuf};
fn main() {
    println!("cargo:rerun-if-changed=runtime.json");
    println!("cargo:rerun-if-changed=asset-manifest.json");
    let manifest: serde_json::Value = serde_json::from_slice(&fs::read("asset-manifest.json").expect("asset manifest")).expect("valid asset manifest");
    let root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let mut source = String::from("pub static EMBEDDED: &[(&str, &[u8])] = &[\n");
    for item in manifest["files"].as_array().expect("manifest files array") {
        let rel = item["path"].as_str().expect("manifest file path");
        let path = root.join("assets").join(rel);
        println!("cargo:rerun-if-changed={}", path.display());
        source.push_str(&format!("({:?}, include_bytes!({:?}) as &[u8]),\n", rel, path.to_string_lossy()));
    }
    source.push_str("];\n");
    fs::write(PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("embedded.rs"), source).expect("write embedded table");
    tauri_build::build();
}
